[package]
name = "truckio_server"
version = "0.1.0"
authors = ["schneki <schneki@protonmail.com>"]

[dependencies]
rand = "0.5.0-pre.1"
ws = "0.7.6"
serde = "1.0.42"
serde_derive = "1.0.43"
serde_json = "1.0.16"
cgmath = "0.16.1"
